export enum GameEvent {
    PlayCreature = "PlayCreature",
    UseCreature = "UseCreature",
    DiscardCreature = "DiscardCreature",
    MoveCreatureToHand = "MoveCreatureToHand",
    AlterCreatureDamage = "AlterCreatureDamage",
    AlterCreaturePower = "AlterCreaturePower",
    MoveCreatureRight = "MoveCreatureRight",
    MoveCreatureLeft = "MoveCreatureLeft",
    CaptureAmber = "CaptureAmber",
    ToggleStun = "ToggleStun",
    ToggleTaunt = "ToggleTaunt",
    ToggleDoomToken = "ToggleDoomToken",

    PlayArtifact = "PlayArtifact",
    UseArtifact = "UseArtifact",
    DiscardArtifact = "DiscardArtifact",
    MoveArtifactToHand = "MoveArtifactToHand",

    PlayUpgrade = "PlayUpgrade",
    PlayAction = "PlayAction",

    DrawCard = "DrawCard",
    DrawFromDiscard = "DrawFromDiscard",
    MoveCardFromDiscardToHand = "MoveCardFromDiscardToHand",
    MoveCardFromArchiveToHand = "MoveCardFromArchiveToHand",
    MoveCardFromDrawPileToHand = "MoveCardFromDrawPileToHand",
    ArchiveCard = "ArchiveCard",
    TakeArchive = "TakeArchive",
    DiscardCard = "DiscardCard",
    PurgeCard = "PurgeCard",
    PutCardOnDrawPile = "PutCardOnDrawPile",
    ShuffleDeck = "ShuffleDeck",
    ShuffleDiscardIntoDeck = "ShuffleDiscardIntoDeck",
    AddAmberToCard = "AddAmberToCard",
    AlterPlayerAmber = "AlterPlayerAmber",
    AlterPlayerChains = "AlterPlayerChains",
    ForgeKey = "ForgeKey",
    UnForgeKey = "UnForgeKey",
    EndTurn = "EndTurn",
}
