enum ImageKey {
    CARDBACK = "cardback",
    UNFORGED_KEY = "unforged-key",
    FORGED_KEY = "forged-key",
    DAMAGE_TOKEN = "damage-token",
    AMBER_TOKEN = "amber-token",
    STUN_TOKEN = "stun-token",
    ARMOR_TOKEN = "armor-token",
    POWER_TOKEN = "power-token",
    CHAINS = "chains",
    DOOM_TOKEN = "doom-token",
    UNDER_CONSTRUCTION = "under-construction",
    CARD_POWER = "card-power",
    ENHANCED_CARD_POWER = "enhanced-card-power",
    GREEN_CARD_GLOW = "green-card-glow",
    ORANGE_CARD_GLOW = "orange-card-glow",
    BLUE_CARD_GLOW = "blue-card-glow",
    BLUE_CARD_GLOW_SMALL = "blue-card-glow-small",
    MAVERICK = "maverick",
    LEGACY = "legacy",
    BROBNAR = "Brobnar",
    DIS = "Dis",
    LOGOS = "Logos",
    MARS = "Mars",
    SAURIAN = "Saurian",
    SANCTUM = "Sanctum",
    STAR_ALLIANCE = "Star Alliance",
    SHADOWS = "Shadows",
    UNTAMED = "Untamed",
}

export default ImageKey
